### ISSUE TITLE
Clean up / document repo

### ISSUE THREAD

**Issue by jhofman** [msr-ds3/immigrant-news-2024-group-2#1]
Just a quick reminder to put the finishing touches on your repo. I'd recommend renaming some files and then writing a nice comprehensive readme. Also, check that it all "just works" if you download a fresh copy of the repo. 

You can take a look at some of the other groups to see how they've structured things.

It takes a bit of time but is very worthwhile!

**Comment by fabio-pecora** [comment]
Yes Jake! I’m working on the readme right now, thanks for the advice!

Fabio

**Comment by jennyw23** [comment]
I think you updated it, but we're missing the link in the Results section: `The results of the reproduction and extension can be seen here`. Good work!

In markdown you can add a hyperlink like [here](url here)

**Comment by MattMunoz** [comment]
The complete r file hasn't been pushed yet. I'll finish it today and push it so I can link it to the section

**Comment by MattMunoz** [comment]
The completed markdown on git and Rmarkdown/HTML files have been pushed and linked. I'll review it in a few days with some fresh eyes to make any necessary updates or corrections. Please let me know if there are any suggested changes or improvements. THank you, everyone!!!!!
